# Generated by Django 4.2.7 on 2024-01-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('balance', models.BigIntegerField()),
                ('agree', models.BooleanField()),
                ('date', models.DateField()),
                ('dateAndTime', models.DateTimeField()),
                ('age', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('email', models.EmailField(max_length=254)),
                ('genericIP', models.GenericIPAddressField()),
                ('image_field', models.ImageField(upload_to='upload/')),
            ],
        ),
    ]
